### ISSUE TITLE
[Missing Feature] Multilingual support

### ISSUE THREAD

**Issue by pauljenny** [WCell/WCell#13]
Hi,
I'm french but WCell doesn't have any multilingual support , why ?
It could help to develop WCell. So I have a suggestion :
Why do you add a multilingual support with files .xml instead of the database which the other emulators use ?
If you accept it, I can begin to work on it.

If you don't understand, this is the traduction in french :
Pourquoi WCell n'a pas de support multi-lingues ?
Cela pourrait aider pour développer WCell. Donc j'ai une suggestion :
Pourquoi ne pas ajouter un support multi-lingues avec des fichiers .xml à la place de la base de données que les autres émulateurs utilisent.
Si vous acceptez, je peux commencer à travailler dessus.

**Comment by VillemP** [comment]
Shyax, you have misunderstood the use of the xml files. Those match the fields of your tables in your database to WCell's internal variables. This means one can easily change the content provider and support several content projects at the same time.
Please read this article: http://wiki.wcell.org/index.php?title=Supported_Databases

**Comment by pauljenny** [comment]
Ok thanks, you are right. 
I don't see the system.
Sorry ;)

**Comment by alexrp** [comment]
There are localization files. Check WCell.RealmServer\Localization and WCell.AuthServer\Localization. These are where you'll want to translate WCell itself.

As for the database - donnu if we support that.

**Comment by Domiii** [comment]
Thanks for the offer, I will try to give you the code, to get cracking. Its  going to be very simple: You will have a file for every language (XML or other) and essentially all one has to do is to go over the code, take out the hardcoded strings and replace them with a key, which will be looked up automatically, depending on the server's and/or client's locale. Most of the requirements are already in the core.

If you can, please come by our IRC channel and we can discuss this in more detail.

EDIT: The Localization folders that Zor mentioned are only useful for log messages, since the default C# resource files cannot be translated dynamically (ie on a per-client basis), which is what we need.

**Comment by pauljenny** [comment]
Domii, you understood what I would like to do.

**Comment by Domiii** [comment]
Added it. Please see latest commit for details.
You can add new language files, as defined names Locale.xml where all valid names for "Locale" are defined in the ClientLocale enum (eg French.xml or ChineseTraditional.xml etc)
