### ISSUE TITLE
Item count and bags.

### ISSUE THREAD

**Issue by ramyalexis** [WCell/WCell#8]
Ok...lets create 4 bags for example with item add command.
And try to put this stack of bags (they would display as 4 bags in one unit) in to empty slot for bags.
Ouch! It puts in empty slot and suddanly became 1 bag! All three other bags are dissapier..
Shoud rise error telling something like "cant do that" (not sure about it) and asking to divide stack and put only one bag in slot..

**Comment by VillemP** [comment]
This isn't an issue, bags shouldn't stack (they stack because of the item add command)

**Comment by ramyalexis** [comment]
yes they do but they cant puts in bag slot (i mean 5 bag slot ) all 4 together with dissapiaring all of them exept one

**Comment by Domiii** [comment]
The stack does not disappear, but the GUI only fails to display a stack of bags in a bag slot. Once you drag them back, the stack number probably disappears. Even if it doesn't - since it can only be caused by a GM command on a rare (and pointless) occasion, and has no serious implications, it is not worth being fixed imo
